### ISSUE TITLE
new feature updated 2

### ISSUE THREAD

**Issue by chiliproject-eu-updates** [chiliproject-eu/test#22]
ChiliProject.eu issue URL: http://www.chiliproject.goto10.net/issues/5

desc

**Comment by chiliproject-eu-updates** [comment]
From: ChiliProject.eu Admin (http://localhost:3001/users/1)

ADD COMMENT

**Comment by svoboda-jan** [comment]
add comment 2

**Comment by svoboda-jan** [comment]
NEW COMMENT :+1:  Hello

**Comment by svoboda-jan** [comment]
Another test

**Comment by svoboda-jan** [comment]
test CORRECT user :+1:
