### ISSUE TITLE
test new user

### ISSUE THREAD

**Issue by svoboda-jan** [chiliproject-eu/test#30]
**From:** Anonymní (http://www.chiliproject.goto10.net/issues/27)

**From:** svoboda-jan (https://github.com/svoboda-jan)

**Comment by chiliproject-eu-updates** [comment]
comment

**Comment by svoboda-jan** [comment]
comment

**Comment by chiliproject-eu-updates** [comment]
**From:** ChiliProject.eu Admin (http://www.chiliproject.goto10.net/issues/26)

comment

**Comment by chiliproject-eu-updates** [comment]
**From:** ChiliProject.eu Admin (http://www.chiliproject.goto10.net/issues/26)

comment 2

**Comment by chiliproject-eu-updates** [comment]
comment from github
