### ISSUE TITLE
test_issue

### ISSUE THREAD

**Issue by svoboda-jan** [chiliproject-eu/test#32]
**From:** Anonymní (http://www.chiliproject.goto10.net/issues/29)

**From:** svoboda-jan (https://github.com/svoboda-jan)

test_issue_description

**Comment by svoboda-jan** [comment]
test_issue_comment

**Comment by svoboda-jan** [comment]
test_issue_comment 2

**Comment by svoboda-jan** [comment]
test_issue_comment 3

**Comment by svoboda-jan** [comment]
test_issue_comment 4

**Comment by svoboda-jan** [comment]
test_issue_comment 5

**Comment by chiliproject-eu-updates** [comment]
**From:** ChiliProject.eu Admin (http://www.chiliproject.goto10.net/issues/29)

redmine comment
