### ISSUE TITLE
github

### ISSUE THREAD

**Issue by svoboda-jan** [chiliproject-eu/test#42]
**From:** Anonymní (http://www.chiliproject.goto10.net/issues/53)

**From:** svoboda-jan (https://github.com/svoboda-jan)

desc

**Comment by chiliproject-eu-updates** [comment]
**From:** ChiliProject.eu Admin (http://www.chiliproject.goto10.net/issues/53)

redmine comment

**Comment by chiliproject-eu-updates** [comment]
**From:** ChiliProject.eu Admin (http://www.chiliproject.goto10.net/issues/53)

redmine comment 2

**Comment by svoboda-jan** [comment]
github comment
